# Generated by Django 5.0.6 on 2024-05-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandForm',
            new_name='LandModel',
        ),
    ]
